site_name: Paper2SW
site_description: Predict super-weights directly from technical papers
site_url: https://ash-blanc.github.io/paper2sw/
repo_url: https://github.com/Ash-Blanc/paper2sw
repo_name: Ash-Blanc/paper2sw

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI: cli.md
  - Python API: python-api.md
  - Features: features.md
  - Configuration: configuration.md
  - Contributing: contributing.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - header.autohide
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.footnote.tooltips
    - content.action.edit
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - glightbox
  - minify

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ash-Blanc/paper2sw
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/extra.js