site_name: Paper2SW
site_description: Predict super-weights directly from technical papers
site_url: https://ash-blanc.github.io/Paper2SW/
repo_url: https://github.com/Ash-Blanc/Paper2SW
repo_name: Ash-Blanc/Paper2SW

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI: cli.md
  - Python API: python-api.md
  - Features: features.md
  - Configuration: configuration.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: indigo

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - def_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ash-Blanc/Paper2SW